// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: save.proto

package com.oxchains.message.grpc.lib;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lib.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 这是要保存到数据库的字段
   * </pre>
   *
   * <code>optional int64 informType = 1;</code>
   */
  long getInformType();

  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>optional int32 messageType = 2;</code>
   */
  int getMessageType();

  /**
   * <pre>
   * 接受者Id
   * </pre>
   *
   * <code>optional int64 receiverId = 3;</code>
   */
  long getReceiverId();

  /**
   * <pre>
   * 消息主体
   * </pre>
   *
   * <code>optional string message = 4;</code>
   */
  String getMessage();
  /**
   * <pre>
   * 消息主体
   * </pre>
   *
   * <code>optional string message = 4;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 订单ID
   * </pre>
   *
   * <code>optional string orderId = 5;</code>
   */
  String getOrderId();
  /**
   * <pre>
   * 订单ID
   * </pre>
   *
   * <code>optional string orderId = 5;</code>
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <pre>
   * 发送者Id，如果是系统就是0
   * </pre>
   *
   * <code>optional int64 sendId = 6;</code>
   */
  long getSendId();

  /**
   * <pre>
   * 项目标识
   * </pre>
   *
   * <code>optional string logo = 7;</code>
   */
  String getLogo();
  /**
   * <pre>
   * 项目标识
   * </pre>
   *
   * <code>optional string logo = 7;</code>
   */
  com.google.protobuf.ByteString
      getLogoBytes();

  /**
   * <pre>
   * 设备标识
   * </pre>
   *
   * <code>optional string registrationId = 8;</code>
   */
  String getRegistrationId();
  /**
   * <pre>
   * 设备标识
   * </pre>
   *
   * <code>optional string registrationId = 8;</code>
   */
  com.google.protobuf.ByteString
      getRegistrationIdBytes();

  /**
   * <pre>
   * 通知内容标题
   * </pre>
   *
   * <code>optional string notificationTitle = 9;</code>
   */
  String getNotificationTitle();
  /**
   * <pre>
   * 通知内容标题
   * </pre>
   *
   * <code>optional string notificationTitle = 9;</code>
   */
  com.google.protobuf.ByteString
      getNotificationTitleBytes();

  /**
   * <pre>
   * 通知内容摘要
   * </pre>
   *
   * <code>optional string notificationSummary = 10;</code>
   */
  String getNotificationSummary();
  /**
   * <pre>
   * 通知内容摘要
   * </pre>
   *
   * <code>optional string notificationSummary = 10;</code>
   */
  com.google.protobuf.ByteString
      getNotificationSummaryBytes();

  /**
   * <pre>
   * 消息内容标题
   * </pre>
   *
   * <code>optional string msgTitle = 11;</code>
   */
  String getMsgTitle();
  /**
   * <pre>
   * 消息内容标题
   * </pre>
   *
   * <code>optional string msgTitle = 11;</code>
   */
  com.google.protobuf.ByteString
      getMsgTitleBytes();

  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>optional string msgContent = 12;</code>
   */
  String getMsgContent();
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>optional string msgContent = 12;</code>
   */
  com.google.protobuf.ByteString
      getMsgContentBytes();

  /**
   * <pre>
   * 扩展字段
   * </pre>
   *
   * <code>optional string extrasParam = 13;</code>
   */
  String getExtrasParam();
  /**
   * <pre>
   * 扩展字段
   * </pre>
   *
   * <code>optional string extrasParam = 13;</code>
   */
  com.google.protobuf.ByteString
      getExtrasParamBytes();
}
