// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: save.proto

package com.oxchains.message.grpc.lib;

/**
 * Protobuf type {@code lib.Request}
 */
public  final class Request extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lib.Request)
    RequestOrBuilder {
  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Request() {
    informType_ = 0L;
    messageType_ = 0;
    receiverId_ = 0L;
    message_ = "";
    orderId_ = "";
    sendId_ = 0L;
    logo_ = "";
    registrationId_ = "";
    notificationTitle_ = "";
    notificationSummary_ = "";
    msgTitle_ = "";
    msgContent_ = "";
    extrasParam_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Request(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            informType_ = input.readInt64();
            break;
          }
          case 16: {

            messageType_ = input.readInt32();
            break;
          }
          case 24: {

            receiverId_ = input.readInt64();
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            orderId_ = s;
            break;
          }
          case 48: {

            sendId_ = input.readInt64();
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            logo_ = s;
            break;
          }
          case 66: {
            String s = input.readStringRequireUtf8();

            registrationId_ = s;
            break;
          }
          case 74: {
            String s = input.readStringRequireUtf8();

            notificationTitle_ = s;
            break;
          }
          case 82: {
            String s = input.readStringRequireUtf8();

            notificationSummary_ = s;
            break;
          }
          case 90: {
            String s = input.readStringRequireUtf8();

            msgTitle_ = s;
            break;
          }
          case 98: {
            String s = input.readStringRequireUtf8();

            msgContent_ = s;
            break;
          }
          case 106: {
            String s = input.readStringRequireUtf8();

            extrasParam_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SaveProto.internal_static_lib_Request_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SaveProto.internal_static_lib_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Request.class, Builder.class);
  }

  public static final int INFORMTYPE_FIELD_NUMBER = 1;
  private long informType_;
  /**
   * <pre>
   * 这是要保存到数据库的字段
   * </pre>
   *
   * <code>optional int64 informType = 1;</code>
   */
  public long getInformType() {
    return informType_;
  }

  public static final int MESSAGETYPE_FIELD_NUMBER = 2;
  private int messageType_;
  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>optional int32 messageType = 2;</code>
   */
  public int getMessageType() {
    return messageType_;
  }

  public static final int RECEIVERID_FIELD_NUMBER = 3;
  private long receiverId_;
  /**
   * <pre>
   * 接受者Id
   * </pre>
   *
   * <code>optional int64 receiverId = 3;</code>
   */
  public long getReceiverId() {
    return receiverId_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 4;
  private volatile Object message_;
  /**
   * <pre>
   * 消息主体
   * </pre>
   *
   * <code>optional string message = 4;</code>
   */
  public String getMessage() {
    Object ref = message_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消息主体
   * </pre>
   *
   * <code>optional string message = 4;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    Object ref = message_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDERID_FIELD_NUMBER = 5;
  private volatile Object orderId_;
  /**
   * <pre>
   * 订单ID
   * </pre>
   *
   * <code>optional string orderId = 5;</code>
   */
  public String getOrderId() {
    Object ref = orderId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      orderId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 订单ID
   * </pre>
   *
   * <code>optional string orderId = 5;</code>
   */
  public com.google.protobuf.ByteString
      getOrderIdBytes() {
    Object ref = orderId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      orderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDID_FIELD_NUMBER = 6;
  private long sendId_;
  /**
   * <pre>
   * 发送者Id，如果是系统就是0
   * </pre>
   *
   * <code>optional int64 sendId = 6;</code>
   */
  public long getSendId() {
    return sendId_;
  }

  public static final int LOGO_FIELD_NUMBER = 7;
  private volatile Object logo_;
  /**
   * <pre>
   * 项目标识
   * </pre>
   *
   * <code>optional string logo = 7;</code>
   */
  public String getLogo() {
    Object ref = logo_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      logo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 项目标识
   * </pre>
   *
   * <code>optional string logo = 7;</code>
   */
  public com.google.protobuf.ByteString
      getLogoBytes() {
    Object ref = logo_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      logo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REGISTRATIONID_FIELD_NUMBER = 8;
  private volatile Object registrationId_;
  /**
   * <pre>
   * 设备标识
   * </pre>
   *
   * <code>optional string registrationId = 8;</code>
   */
  public String getRegistrationId() {
    Object ref = registrationId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      registrationId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 设备标识
   * </pre>
   *
   * <code>optional string registrationId = 8;</code>
   */
  public com.google.protobuf.ByteString
      getRegistrationIdBytes() {
    Object ref = registrationId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      registrationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTIFICATIONTITLE_FIELD_NUMBER = 9;
  private volatile Object notificationTitle_;
  /**
   * <pre>
   * 通知内容标题
   * </pre>
   *
   * <code>optional string notificationTitle = 9;</code>
   */
  public String getNotificationTitle() {
    Object ref = notificationTitle_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      notificationTitle_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 通知内容标题
   * </pre>
   *
   * <code>optional string notificationTitle = 9;</code>
   */
  public com.google.protobuf.ByteString
      getNotificationTitleBytes() {
    Object ref = notificationTitle_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      notificationTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTIFICATIONSUMMARY_FIELD_NUMBER = 10;
  private volatile Object notificationSummary_;
  /**
   * <pre>
   * 通知内容摘要
   * </pre>
   *
   * <code>optional string notificationSummary = 10;</code>
   */
  public String getNotificationSummary() {
    Object ref = notificationSummary_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      notificationSummary_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 通知内容摘要
   * </pre>
   *
   * <code>optional string notificationSummary = 10;</code>
   */
  public com.google.protobuf.ByteString
      getNotificationSummaryBytes() {
    Object ref = notificationSummary_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      notificationSummary_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSGTITLE_FIELD_NUMBER = 11;
  private volatile Object msgTitle_;
  /**
   * <pre>
   * 消息内容标题
   * </pre>
   *
   * <code>optional string msgTitle = 11;</code>
   */
  public String getMsgTitle() {
    Object ref = msgTitle_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      msgTitle_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消息内容标题
   * </pre>
   *
   * <code>optional string msgTitle = 11;</code>
   */
  public com.google.protobuf.ByteString
      getMsgTitleBytes() {
    Object ref = msgTitle_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      msgTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSGCONTENT_FIELD_NUMBER = 12;
  private volatile Object msgContent_;
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>optional string msgContent = 12;</code>
   */
  public String getMsgContent() {
    Object ref = msgContent_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      msgContent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>optional string msgContent = 12;</code>
   */
  public com.google.protobuf.ByteString
      getMsgContentBytes() {
    Object ref = msgContent_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      msgContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTRASPARAM_FIELD_NUMBER = 13;
  private volatile Object extrasParam_;
  /**
   * <pre>
   * 扩展字段
   * </pre>
   *
   * <code>optional string extrasParam = 13;</code>
   */
  public String getExtrasParam() {
    Object ref = extrasParam_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      extrasParam_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 扩展字段
   * </pre>
   *
   * <code>optional string extrasParam = 13;</code>
   */
  public com.google.protobuf.ByteString
      getExtrasParamBytes() {
    Object ref = extrasParam_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      extrasParam_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (informType_ != 0L) {
      output.writeInt64(1, informType_);
    }
    if (messageType_ != 0) {
      output.writeInt32(2, messageType_);
    }
    if (receiverId_ != 0L) {
      output.writeInt64(3, receiverId_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, message_);
    }
    if (!getOrderIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, orderId_);
    }
    if (sendId_ != 0L) {
      output.writeInt64(6, sendId_);
    }
    if (!getLogoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, logo_);
    }
    if (!getRegistrationIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, registrationId_);
    }
    if (!getNotificationTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, notificationTitle_);
    }
    if (!getNotificationSummaryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, notificationSummary_);
    }
    if (!getMsgTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, msgTitle_);
    }
    if (!getMsgContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, msgContent_);
    }
    if (!getExtrasParamBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, extrasParam_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (informType_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, informType_);
    }
    if (messageType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, messageType_);
    }
    if (receiverId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, receiverId_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, message_);
    }
    if (!getOrderIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, orderId_);
    }
    if (sendId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, sendId_);
    }
    if (!getLogoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, logo_);
    }
    if (!getRegistrationIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, registrationId_);
    }
    if (!getNotificationTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, notificationTitle_);
    }
    if (!getNotificationSummaryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, notificationSummary_);
    }
    if (!getMsgTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, msgTitle_);
    }
    if (!getMsgContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, msgContent_);
    }
    if (!getExtrasParamBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, extrasParam_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Request)) {
      return super.equals(obj);
    }
    Request other = (Request) obj;

    boolean result = true;
    result = result && (getInformType()
        == other.getInformType());
    result = result && (getMessageType()
        == other.getMessageType());
    result = result && (getReceiverId()
        == other.getReceiverId());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && getOrderId()
        .equals(other.getOrderId());
    result = result && (getSendId()
        == other.getSendId());
    result = result && getLogo()
        .equals(other.getLogo());
    result = result && getRegistrationId()
        .equals(other.getRegistrationId());
    result = result && getNotificationTitle()
        .equals(other.getNotificationTitle());
    result = result && getNotificationSummary()
        .equals(other.getNotificationSummary());
    result = result && getMsgTitle()
        .equals(other.getMsgTitle());
    result = result && getMsgContent()
        .equals(other.getMsgContent());
    result = result && getExtrasParam()
        .equals(other.getExtrasParam());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + INFORMTYPE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInformType());
    hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMessageType();
    hash = (37 * hash) + RECEIVERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getReceiverId());
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + ORDERID_FIELD_NUMBER;
    hash = (53 * hash) + getOrderId().hashCode();
    hash = (37 * hash) + SENDID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSendId());
    hash = (37 * hash) + LOGO_FIELD_NUMBER;
    hash = (53 * hash) + getLogo().hashCode();
    hash = (37 * hash) + REGISTRATIONID_FIELD_NUMBER;
    hash = (53 * hash) + getRegistrationId().hashCode();
    hash = (37 * hash) + NOTIFICATIONTITLE_FIELD_NUMBER;
    hash = (53 * hash) + getNotificationTitle().hashCode();
    hash = (37 * hash) + NOTIFICATIONSUMMARY_FIELD_NUMBER;
    hash = (53 * hash) + getNotificationSummary().hashCode();
    hash = (37 * hash) + MSGTITLE_FIELD_NUMBER;
    hash = (53 * hash) + getMsgTitle().hashCode();
    hash = (37 * hash) + MSGCONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getMsgContent().hashCode();
    hash = (37 * hash) + EXTRASPARAM_FIELD_NUMBER;
    hash = (53 * hash) + getExtrasParam().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lib.Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lib.Request)
      RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SaveProto.internal_static_lib_Request_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SaveProto.internal_static_lib_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Request.class, Builder.class);
    }

    // Construct using com.oxchains.message.grpc.lib.Request.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      informType_ = 0L;

      messageType_ = 0;

      receiverId_ = 0L;

      message_ = "";

      orderId_ = "";

      sendId_ = 0L;

      logo_ = "";

      registrationId_ = "";

      notificationTitle_ = "";

      notificationSummary_ = "";

      msgTitle_ = "";

      msgContent_ = "";

      extrasParam_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SaveProto.internal_static_lib_Request_descriptor;
    }

    public Request getDefaultInstanceForType() {
      return Request.getDefaultInstance();
    }

    public Request build() {
      Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public Request buildPartial() {
      Request result = new Request(this);
      result.informType_ = informType_;
      result.messageType_ = messageType_;
      result.receiverId_ = receiverId_;
      result.message_ = message_;
      result.orderId_ = orderId_;
      result.sendId_ = sendId_;
      result.logo_ = logo_;
      result.registrationId_ = registrationId_;
      result.notificationTitle_ = notificationTitle_;
      result.notificationSummary_ = notificationSummary_;
      result.msgTitle_ = msgTitle_;
      result.msgContent_ = msgContent_;
      result.extrasParam_ = extrasParam_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Request) {
        return mergeFrom((Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Request other) {
      if (other == Request.getDefaultInstance()) return this;
      if (other.getInformType() != 0L) {
        setInformType(other.getInformType());
      }
      if (other.getMessageType() != 0) {
        setMessageType(other.getMessageType());
      }
      if (other.getReceiverId() != 0L) {
        setReceiverId(other.getReceiverId());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (!other.getOrderId().isEmpty()) {
        orderId_ = other.orderId_;
        onChanged();
      }
      if (other.getSendId() != 0L) {
        setSendId(other.getSendId());
      }
      if (!other.getLogo().isEmpty()) {
        logo_ = other.logo_;
        onChanged();
      }
      if (!other.getRegistrationId().isEmpty()) {
        registrationId_ = other.registrationId_;
        onChanged();
      }
      if (!other.getNotificationTitle().isEmpty()) {
        notificationTitle_ = other.notificationTitle_;
        onChanged();
      }
      if (!other.getNotificationSummary().isEmpty()) {
        notificationSummary_ = other.notificationSummary_;
        onChanged();
      }
      if (!other.getMsgTitle().isEmpty()) {
        msgTitle_ = other.msgTitle_;
        onChanged();
      }
      if (!other.getMsgContent().isEmpty()) {
        msgContent_ = other.msgContent_;
        onChanged();
      }
      if (!other.getExtrasParam().isEmpty()) {
        extrasParam_ = other.extrasParam_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Request parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Request) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long informType_ ;
    /**
     * <pre>
     * 这是要保存到数据库的字段
     * </pre>
     *
     * <code>optional int64 informType = 1;</code>
     */
    public long getInformType() {
      return informType_;
    }
    /**
     * <pre>
     * 这是要保存到数据库的字段
     * </pre>
     *
     * <code>optional int64 informType = 1;</code>
     */
    public Builder setInformType(long value) {
      
      informType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 这是要保存到数据库的字段
     * </pre>
     *
     * <code>optional int64 informType = 1;</code>
     */
    public Builder clearInformType() {
      
      informType_ = 0L;
      onChanged();
      return this;
    }

    private int messageType_ ;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>optional int32 messageType = 2;</code>
     */
    public int getMessageType() {
      return messageType_;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>optional int32 messageType = 2;</code>
     */
    public Builder setMessageType(int value) {
      
      messageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>optional int32 messageType = 2;</code>
     */
    public Builder clearMessageType() {
      
      messageType_ = 0;
      onChanged();
      return this;
    }

    private long receiverId_ ;
    /**
     * <pre>
     * 接受者Id
     * </pre>
     *
     * <code>optional int64 receiverId = 3;</code>
     */
    public long getReceiverId() {
      return receiverId_;
    }
    /**
     * <pre>
     * 接受者Id
     * </pre>
     *
     * <code>optional int64 receiverId = 3;</code>
     */
    public Builder setReceiverId(long value) {
      
      receiverId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 接受者Id
     * </pre>
     *
     * <code>optional int64 receiverId = 3;</code>
     */
    public Builder clearReceiverId() {
      
      receiverId_ = 0L;
      onChanged();
      return this;
    }

    private Object message_ = "";
    /**
     * <pre>
     * 消息主体
     * </pre>
     *
     * <code>optional string message = 4;</code>
     */
    public String getMessage() {
      Object ref = message_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 消息主体
     * </pre>
     *
     * <code>optional string message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消息主体
     * </pre>
     *
     * <code>optional string message = 4;</code>
     */
    public Builder setMessage(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息主体
     * </pre>
     *
     * <code>optional string message = 4;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息主体
     * </pre>
     *
     * <code>optional string message = 4;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private Object orderId_ = "";
    /**
     * <pre>
     * 订单ID
     * </pre>
     *
     * <code>optional string orderId = 5;</code>
     */
    public String getOrderId() {
      Object ref = orderId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        orderId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 订单ID
     * </pre>
     *
     * <code>optional string orderId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      Object ref = orderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 订单ID
     * </pre>
     *
     * <code>optional string orderId = 5;</code>
     */
    public Builder setOrderId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      orderId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 订单ID
     * </pre>
     *
     * <code>optional string orderId = 5;</code>
     */
    public Builder clearOrderId() {
      
      orderId_ = getDefaultInstance().getOrderId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 订单ID
     * </pre>
     *
     * <code>optional string orderId = 5;</code>
     */
    public Builder setOrderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      orderId_ = value;
      onChanged();
      return this;
    }

    private long sendId_ ;
    /**
     * <pre>
     * 发送者Id，如果是系统就是0
     * </pre>
     *
     * <code>optional int64 sendId = 6;</code>
     */
    public long getSendId() {
      return sendId_;
    }
    /**
     * <pre>
     * 发送者Id，如果是系统就是0
     * </pre>
     *
     * <code>optional int64 sendId = 6;</code>
     */
    public Builder setSendId(long value) {
      
      sendId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送者Id，如果是系统就是0
     * </pre>
     *
     * <code>optional int64 sendId = 6;</code>
     */
    public Builder clearSendId() {
      
      sendId_ = 0L;
      onChanged();
      return this;
    }

    private Object logo_ = "";
    /**
     * <pre>
     * 项目标识
     * </pre>
     *
     * <code>optional string logo = 7;</code>
     */
    public String getLogo() {
      Object ref = logo_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        logo_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 项目标识
     * </pre>
     *
     * <code>optional string logo = 7;</code>
     */
    public com.google.protobuf.ByteString
        getLogoBytes() {
      Object ref = logo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        logo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 项目标识
     * </pre>
     *
     * <code>optional string logo = 7;</code>
     */
    public Builder setLogo(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      logo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 项目标识
     * </pre>
     *
     * <code>optional string logo = 7;</code>
     */
    public Builder clearLogo() {
      
      logo_ = getDefaultInstance().getLogo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 项目标识
     * </pre>
     *
     * <code>optional string logo = 7;</code>
     */
    public Builder setLogoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      logo_ = value;
      onChanged();
      return this;
    }

    private Object registrationId_ = "";
    /**
     * <pre>
     * 设备标识
     * </pre>
     *
     * <code>optional string registrationId = 8;</code>
     */
    public String getRegistrationId() {
      Object ref = registrationId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        registrationId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 设备标识
     * </pre>
     *
     * <code>optional string registrationId = 8;</code>
     */
    public com.google.protobuf.ByteString
        getRegistrationIdBytes() {
      Object ref = registrationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        registrationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 设备标识
     * </pre>
     *
     * <code>optional string registrationId = 8;</code>
     */
    public Builder setRegistrationId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      registrationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备标识
     * </pre>
     *
     * <code>optional string registrationId = 8;</code>
     */
    public Builder clearRegistrationId() {
      
      registrationId_ = getDefaultInstance().getRegistrationId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备标识
     * </pre>
     *
     * <code>optional string registrationId = 8;</code>
     */
    public Builder setRegistrationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      registrationId_ = value;
      onChanged();
      return this;
    }

    private Object notificationTitle_ = "";
    /**
     * <pre>
     * 通知内容标题
     * </pre>
     *
     * <code>optional string notificationTitle = 9;</code>
     */
    public String getNotificationTitle() {
      Object ref = notificationTitle_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        notificationTitle_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 通知内容标题
     * </pre>
     *
     * <code>optional string notificationTitle = 9;</code>
     */
    public com.google.protobuf.ByteString
        getNotificationTitleBytes() {
      Object ref = notificationTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        notificationTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 通知内容标题
     * </pre>
     *
     * <code>optional string notificationTitle = 9;</code>
     */
    public Builder setNotificationTitle(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      notificationTitle_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通知内容标题
     * </pre>
     *
     * <code>optional string notificationTitle = 9;</code>
     */
    public Builder clearNotificationTitle() {
      
      notificationTitle_ = getDefaultInstance().getNotificationTitle();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通知内容标题
     * </pre>
     *
     * <code>optional string notificationTitle = 9;</code>
     */
    public Builder setNotificationTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      notificationTitle_ = value;
      onChanged();
      return this;
    }

    private Object notificationSummary_ = "";
    /**
     * <pre>
     * 通知内容摘要
     * </pre>
     *
     * <code>optional string notificationSummary = 10;</code>
     */
    public String getNotificationSummary() {
      Object ref = notificationSummary_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        notificationSummary_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 通知内容摘要
     * </pre>
     *
     * <code>optional string notificationSummary = 10;</code>
     */
    public com.google.protobuf.ByteString
        getNotificationSummaryBytes() {
      Object ref = notificationSummary_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        notificationSummary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 通知内容摘要
     * </pre>
     *
     * <code>optional string notificationSummary = 10;</code>
     */
    public Builder setNotificationSummary(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      notificationSummary_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通知内容摘要
     * </pre>
     *
     * <code>optional string notificationSummary = 10;</code>
     */
    public Builder clearNotificationSummary() {
      
      notificationSummary_ = getDefaultInstance().getNotificationSummary();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通知内容摘要
     * </pre>
     *
     * <code>optional string notificationSummary = 10;</code>
     */
    public Builder setNotificationSummaryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      notificationSummary_ = value;
      onChanged();
      return this;
    }

    private Object msgTitle_ = "";
    /**
     * <pre>
     * 消息内容标题
     * </pre>
     *
     * <code>optional string msgTitle = 11;</code>
     */
    public String getMsgTitle() {
      Object ref = msgTitle_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgTitle_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 消息内容标题
     * </pre>
     *
     * <code>optional string msgTitle = 11;</code>
     */
    public com.google.protobuf.ByteString
        getMsgTitleBytes() {
      Object ref = msgTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消息内容标题
     * </pre>
     *
     * <code>optional string msgTitle = 11;</code>
     */
    public Builder setMsgTitle(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgTitle_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息内容标题
     * </pre>
     *
     * <code>optional string msgTitle = 11;</code>
     */
    public Builder clearMsgTitle() {
      
      msgTitle_ = getDefaultInstance().getMsgTitle();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息内容标题
     * </pre>
     *
     * <code>optional string msgTitle = 11;</code>
     */
    public Builder setMsgTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msgTitle_ = value;
      onChanged();
      return this;
    }

    private Object msgContent_ = "";
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>optional string msgContent = 12;</code>
     */
    public String getMsgContent() {
      Object ref = msgContent_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgContent_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>optional string msgContent = 12;</code>
     */
    public com.google.protobuf.ByteString
        getMsgContentBytes() {
      Object ref = msgContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>optional string msgContent = 12;</code>
     */
    public Builder setMsgContent(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgContent_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>optional string msgContent = 12;</code>
     */
    public Builder clearMsgContent() {
      
      msgContent_ = getDefaultInstance().getMsgContent();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>optional string msgContent = 12;</code>
     */
    public Builder setMsgContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msgContent_ = value;
      onChanged();
      return this;
    }

    private Object extrasParam_ = "";
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>optional string extrasParam = 13;</code>
     */
    public String getExtrasParam() {
      Object ref = extrasParam_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        extrasParam_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>optional string extrasParam = 13;</code>
     */
    public com.google.protobuf.ByteString
        getExtrasParamBytes() {
      Object ref = extrasParam_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        extrasParam_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>optional string extrasParam = 13;</code>
     */
    public Builder setExtrasParam(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extrasParam_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>optional string extrasParam = 13;</code>
     */
    public Builder clearExtrasParam() {
      
      extrasParam_ = getDefaultInstance().getExtrasParam();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>optional string extrasParam = 13;</code>
     */
    public Builder setExtrasParamBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extrasParam_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:lib.Request)
  }

  // @@protoc_insertion_point(class_scope:lib.Request)
  private static final Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Request();
  }

  public static Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Request>
      PARSER = new com.google.protobuf.AbstractParser<Request>() {
    public Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Request> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  public Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

