// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: save.proto

package com.oxchains.message.grpc.lib;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lib.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool message = 1;</code>
   */
  boolean getMessage();
}
