// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: save.proto

package com.oxchains.message.grpc.lib;

public final class SaveProto {
  private SaveProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lib_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lib_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lib_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lib_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nsave.proto\022\003lib\"\221\002\n\007Request\022\022\n\ninformT" +
      "ype\030\001 \001(\003\022\023\n\013messageType\030\002 \001(\005\022\022\n\nreceiv" +
      "erId\030\003 \001(\003\022\017\n\007message\030\004 \001(\t\022\017\n\007orderId\030\005" +
      " \001(\t\022\016\n\006sendId\030\006 \001(\003\022\014\n\004logo\030\007 \001(\t\022\026\n\016re" +
      "gistrationId\030\010 \001(\t\022\031\n\021notificationTitle\030" +
      "\t \001(\t\022\033\n\023notificationSummary\030\n \001(\t\022\020\n\010ms" +
      "gTitle\030\013 \001(\t\022\022\n\nmsgContent\030\014 \001(\t\022\023\n\013extr" +
      "asParam\030\r \001(\t\"\033\n\010Response\022\017\n\007message\030\001 \001" +
      "(\0102/\n\006Simple\022%\n\004Save\022\014.lib.Request\032\r.lib" +
      ".Response\"\000B1\n\035com.oxchains.message.grpc",
      ".libB\tSaveProtoP\001\242\002\002SPb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lib_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lib_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lib_Request_descriptor,
        new String[] { "InformType", "MessageType", "ReceiverId", "Message", "OrderId", "SendId", "Logo", "RegistrationId", "NotificationTitle", "NotificationSummary", "MsgTitle", "MsgContent", "ExtrasParam", });
    internal_static_lib_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lib_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lib_Response_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
